export enum RemmeMethods {
    certificate = "certificate",
    certificateStore = "certificate/store",
    token = "token",
    batchStatus = "batch_status",
    personal = "personal",
    userCertificates = "user",
    atomicSwap = "atomic-swap",
    atomicSwapInit = "atomic-swap/init",
    atomicSwapApprove = "atomic-swap/approve",
    atomicSwapExpire = "atomic-swap/expire",
    atomicSwapSecretLock = "atomic-swap/set-secret-lock",
    atomicSwapClose = "atomic-swap/close",
    atomicSwapPublicKey = "atomic-swap/pub-key-encryption",
}
